[project]
name = "consulta_amigable"
version = "0.1.2"
description = "Web scraping del SIAF-Consulta Amigable con opción interactiva para crear rutas"
readme = "README.md"
requires-python = ">=3.10" # Por los type hints

dependencies = [
    "pandas",
    "playwright",
    "pydantic>=2.12.5",
    "PyYAML",
    "questionary",
    "rich",
    "ubigeos_peru",
]


[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.1.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
]

# Instalar la librería localmente al ejecutar uv sync
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/consulta_amigable"]


[dependency-groups]
dev = [
    "autoflake>=2.3.1",
    "isort>=7.0.0",
    "pre-commit>=4.5.1",
    "ruff>=0.14.14",
]
